### PR TITLE
Fix GetAllProjects() with subfolders of folders in VS2017

### PR DESCRIPTION
**Pull request by sliddington**

### CODE REVIEW

**Comment by Eagle3386** [comment]
I'm wondering how @sliddington got this built, because he removed
```
public static EnvDTE.Project GetProject(EnvDTE.DTE dte, string projectName)
{
	return GetAllProjects(dte).Where(p=>p.Name == projectName).First();
}
```
which is still utilized in, e. g. `GetTemplateProjectItem`..

**Review by Eagle3386 — CHANGES_REQUESTED** [review]
See https://github.com/renegadexx/T4.Helper/pull/18#issuecomment-644067778

**Comment by sliddington** [comment]
@Eagle3386 This is so long ago now I don't exactly remember what it was about. I did manually enter the changes into github and my local checkout may not have been at exactly the same point in the history.

I suspect I only removed it because it was unused in my local checkout and it looks fine to leave it in as it was.

**Comment by databinding-thierryiseli** [comment]
Maybe some interesting information for you. We have worked out a new FileManager, which can also be used in .NET Core project: https://github.com/databinding-gmbh/T4.FileManager.VisualStudio. Currently, only the documentation is on GitHub. The code will follow.

**Comment by Eagle3386** [comment]
@databinding-thierryiseli Thanks for the heads-up, but what's the actual ETA for "code will follow"?

**Review by Eagle3386 — CHANGES_REQUESTED** [review]
Lines 1024-1028 must not be deleted, see https://github.com/renegadexx/T4.Helper/pull/18#issuecomment-644797535 for details

**Comment by Eagle3386** [comment]
@sliddington Sorry for kinda "resurrecting" this PR. But since you're stating that you've edited it directly in GitHub, I can see what probably caused this. For reference, I've commented on the code - at least I thought so, but it ended up here. Again, sorry for any inconvenience.

**Comment by sliddington** [comment]
No worries. Good to see some people tidying up this project.

**Comment by databinding-thierryiseli** [comment]
> @databinding-thierryiseli Thanks for the heads-up, but what's the actual ETA for "code will follow"?

The entire code is now on GitHub and includes some user story oriented SpecFlow testing: https://github.com/databinding-gmbh/T4.FileManager.VisualStudio.

**Pull request closed without merging**
